sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y lftp
    - git clone --depth=50 --branch=master git@github.com:PaloAltoNetworks/appframeworklab.wiki.git
install:
    - npm install github-wikito-converter
    - wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz -O $PWD/wkhtmltopdf.tar.xz
    - mkdir wkhtmltopdf
    - tar xf wkhtmltopdf.tar.xz -C $PWD/wkhtmltopdf
    - export PATH=$PWD/wkhtmltopdf/wkhtmltox/bin:$PATH
script:
    - gwtc  -v -f all --css $PWD/appframeworklab.wiki/style/PANW.css $PWD/appframeworklab.wiki --pdf-page-count --logo-img=$PWD/appframeworklab.wiki/img/panw.png --footer "Copyright (C) 2018 - Palo Alto Networks, Inc." -t "Palo Alto Networks Application Framework - Lab Guide"
    - echo ${MYVAR}
    - ls -ltR
