sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y lftp
- export GKEY=$GITHUB_API_KEY
- export BOX_PASS=$BOX_PASSWORD
- export BOX_USER=$BOX_USERNAME
- cp build/build.sh $HOME/bucketbuild.sh
- chmod +x $HOME/bucketbuild.sh
install: 
script:
- $HOME/bucketbuild.sh
- git add -A
- CHCONF=0
- CHANGE=0
- git diff-tree --quiet HEAD -r buckets/appframework-conf.zip || CHCONF=1
- git diff-index --quiet HEAD || CHANGE=1
- echo chconf=${CHCONF}
- echo change=${CHANGE}
- echo GKEY=${GKEY}
- echo BOX_USER=${BOX_USER}
- echo BOX_PASS=${BOX_PASS}
- if [[ "$CHANGE" == "1" ]]; then git remote set-url origin https://$GKEY@github.com/PaloAltoNetworks/appframeworklab.git;  fi
- if [[ "$CHANGE" == "1" ]]; then git commit -m 'autocommit travis [skip ci]'; fi
- if [[ "$CHANGE" == "1" ]]; then git push origin HEAD:master --force; fi
- if [[ "$CHCONF" == "1" ]]; then cat build/lftp-conf.cmd  | sed "s/BOXUSER BOXPASSWORD/${BOX_USER}
  ${BOX_PASS}/" | lftp; fi
env:
  matrix:
  - secure: NR5Bgn/jvv2T0uzOFFfHwabEHLjGBU+kGafzYGs4wSkhE9Q1fmzEWy/nyi2kufl3Y/ieRMzPtgzI2DSb6iGH6Wi/MJ+nhSmIRbUwfD6msa6k2nuJbbcGCgzxxGlDbJbb0JWHusvyWrFFsoEL0Aou+eOT4ZXivRKCyZMw8cAVvw7Oc9E840PaYpvpXFhAqXkzpzAPp5/D3nkM3jeXhh8kVufOAYQoDb6geCq3IApeB+URtDOgT2jrr4VO8dryGrJkrJkVyteMLUCa3s5zSmyOkHTq9qfar81OSZLyotiax51hB8X/BH0lkz7k9/K3XKoVb4ISfIuNb2TnxnrHuB+nmBMqZQ1blh64tG2olxaG2ZrRLtrkCHFFTb0U56NJfuhAvFHeNIM2tzHCG7n7WnG75Ux0Sg5tH4hYvuHLX/f4Pu198Sde5HmjBrbgC80I3avVgBg7bn7c6CMr5ZqTGcCBklj4sHGZvr8OdjJUqltFLJqCYh+XbQYHwulKfTJvUhuFW86R1oPkodibttRLOlpo8WH+hMMhy2J5MhKuoMVV0fVEf0e4VLuKM9Qc4pU4+TrG6xiL5JVP7v2ViZDlcMvTfXNY63x2Kg3xRmJX8byiRpUTojVB3OSe2iaxXs4fsbsP+62EqSoTH7qRvIpcAYBGvcNhMqfsdD1JrNcgwLKQvHI=
  - secure: f8W2+IxNwsEilJg5Pn+NuyHlcvq7yW6w2WaJL6zw/yZKjzrEL//ueNLZYJJ6jdRRNcf1m4gnqnRnJbdrrz7IFXwCZ6Flv5OVAUpwbyyv8wAJmlnXuGQLfQHIeKvrHwNdU4rJhU8Vqh+aG4xpoFC67weO2cmgJDxb9OO0f1FuzHnyRB1YViDPSiZRi8A8bouUZaIYIxTw5MUBJilV5Ae8XcXKX/NENfffXt4iNG0dFtQ+1mfqgwK3seK6FeGCTzltutwyBHznEcOOAY6Fhe0CDyzJ4SvAgsAgjEFBPt3OxPnlt2GkIbXdN9U5bnaYRtTF50Ednc0rMkst2ziXqHwpzN+M6PUkeivFBGwwt1DDhFgzffMb3itTQtInSu73zHXEJ86GRn7dNPVzsqWfmQZwg1MPu0dMLTsZqSRocFYtFICQid4a0nJw3tciiAaPlWbEE6fss6Ke07JeGWtbXMW1VixKwqkM/sV3f5sURs8B8ttFl6+spe4qzVpKM1n6YA/e+gT/VfGa52FaNJWC6n0pM2urQ423dqNSk4WQFpfBmPfivkyY0SGy+5YUrZmCZu+vRO9EV549F3X4NvaybzAByFfGDn10hZX4y4zsAyHbPwgwjEhtM/ykUBZNRpbJkVZ8DE37gehdmVrO+8kqZ9G1T9K8sbnLqcjnSnoqmwj0dPk=
  - secure: J341KaBllZPofyRi6r8PdXlgJTB0oo0POiAuNYhmGLWzNculLR0hglzUH0mCe9kv6f8z8LPcnkRdUzeL4BpVgtsWEIfoC9TBnVtxOFLxQfkgj/B27aUvYsy3/M4hxyQJRPMFz4sDtNgUMfJxEaXqv2tA2ZN9m0tEJROXxSJnTKajiqLWc73YI5E1kmr8wfUsfaP/+4/Zhz+RF566vBDNR45817rHM+1mFe+RnWwqpWghrhzpsRTFcYX0R5zpR6HcMrpiAp6GhIUoLsC1ASvhkG/7CfyyYAGlaFLzeEatrEvpCDNksOLNR41JrUsLopHom2NhV+9PCOYolAMrFuXLHSIAW8HbwkkSq3B4Kij59wC1WKa60QxUh/QoKRmKqvagEcsdsxNZriy5kCQ4KqMAel2Xkpp58v/cp9gxARqV0jreHnA5yLO6RDlYfwcAGGNNEGLovdvjrwbRqCvl8KCxaZWPf1m+YvugAXK4JPpFFbsuZ/pEDRoylT72wLgykYgdhGMY6Ar08pyU3rtRudRmsSICLaheZy6UygOpsm8w7knmh2pxNcZbGvDbqmKHWzuHzCLDba33W96rzMG2izPZQzmuuzpWK3B02SL9DwFyGQQwEqaJQmkEd5wqTXZqO3cLkRb+HdE6zxB8RPBqDgn16sydjVb0pQsfw5UI5o365VE=
